### ISSUE TITLE
“TypeError: Cannot read property 'error' of undefined” when running: fly

### ISSUE THREAD

**Issue by rmariuzzo** [lukeed/fly-esnext#2]
Hello! I'm trying to run the following command:

``` sh
$ ./node_modules/fly/cli.js -f flyfile.js
```

And I receive the following error:

``` sh
stack: 
  - TypeError: Cannot read property 'error' of undefined
  -     at OptionManager.mergeOptions (~/Workspace/abc/node_modules/fly-esnext/node_modules/babel-core/lib/transformation/file/options/option-manager.js 126:28)
  -     at OptionManager.addConfig (~/Workspace/abc/node_modules/fly-esnext/node_modules/babel-core/lib/transformation/file/options/option-manager.js 107:10)
  -     at OptionManager.findConfigs (~/Workspace/abc/node_modules/fly-esnext/node_modules/babel-core/lib/transformation/file/options/option-manager.js 168:35)
  -     at OptionManager.init (~/Workspace/abc/node_modules/fly-esnext/node_modules/babel-core/lib/transformation/file/options/option-manager.js 229:12)
  -     at compile (~/Workspace/abc/node_modules/fly-esnext/node_modules/babel-core/lib/api/register/node.js 117:22)
  -     at normalLoader (~/Workspace/abc/node_modules/fly-esnext/node_modules/babel-core/lib/api/register/node.js 199:14)
  -     at Object.require.extensions.(anonymous function) [as .js] (~/Workspace/abc/node_modules/fly-esnext/node_modules/babel-core/lib/api/register/node.js 216:7)
  -     at Module.load (module.js 458:32)
  -     at tryModuleLoad (module.js 417:12)
  -     at Function.Module._load (module.js 409:3)
message: Cannot read property 'error' of undefined
```

---

The following are my dependencies with their respective version:

``` sh
$ npm list --depth=0
abc@1.0.0 ~/Workspace/abc
├── babel-cli@6.11.4
├── eslint@3.2.2
├── fly@1.3.1
└── fly-esnext@1.0.1
```

**Comment by lukeed** [comment]
Hi! The error reporting is terrible right now, so I think it's actually an error within your Fly task(s) or plugin(s) and it's being caught from within Babel.

Can you post your relevant tasks and/or send a link to a reproducible repo?

Sorry... been meaning to rewrite the entire error section of Fly. 😢

**Comment by rmariuzzo** [comment]
Hey @lukeed! Thanks for your quick reply and interest.

My `flyfile.js` had the following contents:

``` js
var task = module.exports;

task.default = function* () {
    yield this
        .source('src/*.js')
        .target('lib');
};
```

---

I have also tried with the equivalent in es6. I removed `fly-esnext` and everything works smoothly. Not sure if I did something wrong or I missed something.

**Comment by lukeed** [comment]
Hmm.. What's your node version?

**Comment by rmariuzzo** [comment]
``` sh
$ node --version
v6.3.1
```

**Comment by lukeed** [comment]
Ah, ya. I haven’t toyed with v6 yet. I'll jiggle with it tonight. If you wanna revert to node 4 or 5, you'll be good to go

**Comment by rmariuzzo** [comment]
Oh, I see. For now, I will stick with es5. Thanks for all your time and efforts. Keep rocking! Nice library!

**Comment by lukeed** [comment]
Thanks, unfortunately it's been stale for a couple months now due to work and personal projects, but Fly has satisfied all my needs for the last ~8 months

**Comment by rmariuzzo** [comment]
I'm more than willing to collaborate with the development of Fly I will keep an eye on it. One quick question: can you point me out how to rename a file? I mean I want to `target(...)` 2 files: `lib.js` and `lib.min.js`.

**Comment by lukeed** [comment]
You'd just have to construct a second yieldable sequence...for now. 

``` js
yield this.source('a.js').stuff().target('b.js');
yield this.source('b.js').uglify().target('b.min.js');
```

What I've been doing at least.

**Comment by lukeed** [comment]
Also more than willing to work with new contributors! Quite a todo list on Fly, more in my head if none of those suit you.

**Comment by rmariuzzo** [comment]
No problem, I just want to contribute. Tomorrow, I will take a peek at current issues to see what can I take. :) Or if you just want to discuss/assign me something… anything will work.
